import {
  Heart,
  PiggyBank,
  Home,
  CreditCard,
  Landmark,
  ShoppingCart,
  Utensils,
  Coffee,
  Pizza,
  Car,
  Fuel,
  Bus,
  Train,
  Plane,
  ParkingCircle,
  Wrench,
  Zap,
  Wifi,
  Phone,
  Tv,
  Film,
  Music,
  Gamepad2,
  Camera,
  Book,
  GraduationCap,
  Briefcase,
  Building2,
  Dog,
  Cat,
  Baby,
  Shirt,
  Scissors,
  Dumbbell,
  HeartPulse,
  Stethoscope,
  Pill,
  Shield,
  Umbrella,
  Gift,
  Sparkles,
  Palette,
  TreePine,
  Flower2,
  MapPin,
  Luggage,
  Wallet,
  Coins,
  TrendingUp,
  Receipt,
  Banknote,
  DollarSign,
  Building,
  Users,
  PartyPopper,
  Cake,
  Smartphone,
  Laptop,
  Droplet,
  Flame,
  Trash2,
  Hammer,
  Paintbrush,
  Bike,
  Bath,
  Tag,
  type LucideIcon,
} from "lucide-react";

// A curated set of lucide icons relevant to household budget categories -
// used both for auto-matching a category's icon by name and for a future
// icon picker. Keys are stored in category_groups.icon.
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  heart: Heart,
  "piggy-bank": PiggyBank,
  home: Home,
  "credit-card": CreditCard,
  landmark: Landmark,
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  car: Car,
  fuel: Fuel,
  bus: Bus,
  train: Train,
  plane: Plane,
  parking: ParkingCircle,
  wrench: Wrench,
  zap: Zap,
  wifi: Wifi,
  phone: Phone,
  tv: Tv,
  film: Film,
  music: Music,
  gamepad: Gamepad2,
  camera: Camera,
  book: Book,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  building: Building2,
  dog: Dog,
  cat: Cat,
  baby: Baby,
  shirt: Shirt,
  scissors: Scissors,
  dumbbell: Dumbbell,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  shield: Shield,
  umbrella: Umbrella,
  gift: Gift,
  sparkles: Sparkles,
  palette: Palette,
  "tree-pine": TreePine,
  flower: Flower2,
  "map-pin": MapPin,
  luggage: Luggage,
  wallet: Wallet,
  coins: Coins,
  "trending-up": TrendingUp,
  receipt: Receipt,
  banknote: Banknote,
  "dollar-sign": DollarSign,
  building2: Building,
  users: Users,
  party: PartyPopper,
  cake: Cake,
  smartphone: Smartphone,
  laptop: Laptop,
  droplet: Droplet,
  flame: Flame,
  trash: Trash2,
  hammer: Hammer,
  paintbrush: Paintbrush,
  bike: Bike,
  bath: Bath,
  tag: Tag,
};

export const DEFAULT_CATEGORY_ICON = "tag";

// Keyword -> icon key, checked in order against the category's name
// (case-insensitive substring match) when no icon has been explicitly set.
const NAME_HEURISTICS: [pattern: RegExp, icon: string][] = [
  [/giving|charity|donat|tithe|church/i, "heart"],
  [/saving|emergency fund|nest egg/i, "piggy-bank"],
  [/mortgage|rent|housing|home\b/i, "home"],
  [/debt|loan|credit card|student loan|payoff/i, "credit-card"],
  [/bank|checking|savings account/i, "landmark"],
  [/gas.*house|gas bill|electric|utility|utilities|power\b/i, "zap"],
  [/water\b/i, "droplet"],
  [/internet|wifi|broadband/i, "wifi"],
  [/phone|mobile|cell/i, "phone"],
  [/netflix|hulu|disney|streaming|tv\b/i, "tv"],
  [/movie|cinema|film/i, "film"],
  [/music|spotify|apple music/i, "music"],
  [/game|gaming|xbox|playstation|steam/i, "gamepad"],
  [/photo|camera/i, "camera"],
  [/book|kindle|audible/i, "book"],
  [/school|tuition|education|student/i, "graduation-cap"],
  [/work|business|office/i, "briefcase"],
  [/pet care|vet\b/i, "dog"],
  [/cat\b/i, "cat"],
  [/baby|daycare|childcare|kids?\b/i, "baby"],
  [/cloth|apparel|shirt/i, "shirt"],
  [/hair|salon|barber|beauty/i, "scissors"],
  [/gym|fitness|workout/i, "dumbbell"],
  [/health|medical|doctor/i, "heart-pulse"],
  [/dentist|therapy|clinic/i, "stethoscope"],
  [/pharmacy|medicine|prescription/i, "pill"],
  [/insurance/i, "shield"],
  [/gift|present/i, "gift"],
  [/lawn|garden|yard/i, "tree-pine"],
  [/flower/i, "flower"],
  [/travel|vacation|trip|hotel/i, "luggage"],
  [/uber|lyft|taxi|rideshare/i, "car"],
  [/gas\b|fuel/i, "fuel"],
  [/bus\b|transit/i, "bus"],
  [/train|rail|subway/i, "train"],
  [/flight|airline|airfare/i, "plane"],
  [/parking/i, "parking"],
  [/repair|maintenance|wrench/i, "wrench"],
  [/tools|hardware|diy/i, "hammer"],
  [/paint/i, "paintbrush"],
  [/bike|cycling/i, "bike"],
  [/grocery|groceries|market/i, "shopping-cart"],
  [/restaurant|dining|takeout|delivery/i, "utensils"],
  [/coffee|cafe/i, "coffee"],
  [/pizza|fast food/i, "pizza"],
  [/party|celebration|event/i, "party"],
  [/birthday|cake/i, "cake"],
  [/subscription|app\b/i, "smartphone"],
  [/computer|laptop|software/i, "laptop"],
  [/trash|garbage|waste/i, "trash"],
  [/investment|stocks|retirement|401k|brokerage/i, "trending-up"],
  [/tax|irs/i, "receipt"],
  [/cash|allowance/i, "banknote"],
  [/misc|other/i, "dollar-sign"],
];

export function resolveCategoryIconKey(name: string, storedIcon?: string | null): string {
  if (storedIcon && storedIcon in CATEGORY_ICONS) return storedIcon;

  for (const [pattern, icon] of NAME_HEURISTICS) {
    if (pattern.test(name)) return icon;
  }

  return DEFAULT_CATEGORY_ICON;
}

export function CategoryIcon({
  name,
  storedIcon,
  className,
}: {
  name: string;
  storedIcon?: string | null;
  className?: string;
}) {
  const Icon = CATEGORY_ICONS[resolveCategoryIconKey(name, storedIcon)];
  return <Icon className={className} />;
}
